/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.cine.iu;

import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mx.itson.cine.entidades.Funcion;

/**
 *
 * @author luism
 */
public class FuncionTabla extends javax.swing.JFrame {

    private DefaultTableModel funcionModel;

    /**
     * Creates new form FuncionTabla
     */
    public FuncionTabla() {
        initComponents();
        funcionModel = (DefaultTableModel) tblFunciones.getModel();
        actualizarTabla();
    }
    public void actualizarTabla() {
    // Limpiamos la tabla antes de agregar nuevos datos
    funcionModel.setRowCount(0);

    try {
        List<Funcion> funciones = Funcion.getAll();
        
        for (Funcion f : funciones) {
            // Imprimir algunas propiedades para depuración
                System.out.println("ID: " + f.getId());
                System.out.println("Empleado: " + f.getEmpleado().getId());
                System.out.println("Pelicula: " + f.getPelicula());
                System.out.println("Sala: " + f.getSala().getId());
                System.out.println("Horario: " + f.getHorario());

                // Añadir la fila a la tabla
                funcionModel.addRow(new Object[]{
                    f.getId(),
                    f.getEmpleado().getNombre(),
                    f.getPelicula().getTitulo(),
                    f.getSala().getId(),
                    f.getHorario().getFecha()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
/*
    private void inicializarTabla() {
        funcionModel = new DefaultTableModel();
        funcionModel.addColumn("ID");
        funcionModel.addColumn("Empleado");
        funcionModel.addColumn("Pelicula");
        funcionModel.addColumn("Sala");
        funcionModel.addColumn("Horario");

        // Establecer el modelo en la tabla
        tblFunciones.setModel(funcionModel);
    }
/*
    public void actualizarTabla() {
        // Obtener la lista de funciones desde la base de datos
        List<Funcion> funciones = Funcion.getAll();
        System.out.println("Número de funciones recuperadas: " + funciones.size());
        // Limpiar el modelo de la tabla antes de agregar nuevos datos
        funcionModel.setRowCount(0);

        // Agregar filas al modelo de la tabla
        for (Funcion funcion : funciones) {
            Object[] rowData = {
                    funcion.getId(),
                    funcion.getEmpleado().toString(),
                    funcion.getPelicula().toString(),
                    funcion.getSala().toString(),
                    funcion.getHorario().toString()
            };
            funcionModel.addRow(rowData);
        }
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFunciones = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Empleado", "Pelicula", "Sala", "Horario"
            }
        ));
        jScrollPane1.setViewportView(tblFunciones);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Funciones");

        btnCrear.setText("Crear");

        btnEliminar.setText("Eliminar");

        btnActualizar.setText("Actualizar");
        btnActualizar.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar)
                            .addComponent(btnCrear))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblFunciones;
    // End of variables declaration//GEN-END:variables
}
